---

- name: Install docker dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Trust docker's key
  become: true
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker's apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable

- name: Install docker
  apt:
    name: docker-ce
    state: latest

- name: Install docker-compose
  apt:
    name: docker-compose
    state: latest
  when: "docker-compose"
